
package editor.buildingeditor2;

import editor.handler.MapEditorHandler;
import javafx.application.Platform;
import javafx.stage.DirectoryChooser;
import utils.FileChooserUtils;

import java.io.File;
import javax.swing.*;

/**
 * @author Trifindo
 */
public class BuildingEditorChooser {

    public static void loadGame(MapEditorHandler handler) {
        File lastDir = handler.getLastBuildDirectoryUsed() != null
                ? new File(handler.getLastBuildDirectoryUsed())
                : null;

        FileChooserUtils.selectDirectory(
                "Select the game's main folder that was generated with SDSME or similar",
                lastDir,
                selectedDirectory -> {
                    if (selectedDirectory == null) return; // Utilisateur a annulé

                    String folderPath = selectedDirectory.getPath();

                    if (isDPPtFolder(folderPath)) {
                        handler.setLastBuildDirectoryUsed(folderPath);
                        BuildHandlerDPPt buildHandler = new BuildHandlerDPPt(folderPath);
                        final BuildingEditorDialogDPPt dialogDPPt = new BuildingEditorDialogDPPt(handler.getMainFrame());
                        dialogDPPt.init(handler, buildHandler);
                        dialogDPPt.loadGame(selectedDirectory.getPath());
                        dialogDPPt.loadCurrentNsbmd();
                        dialogDPPt.updateView();
                        dialogDPPt.setLocationRelativeTo(handler.getMainFrame());
                        dialogDPPt.setVisible(true);
                    } else if (isHGSSFolder(folderPath)) {
                        handler.setLastBuildDirectoryUsed(folderPath);
                        BuildHandlerHGSS buildHandler = new BuildHandlerHGSS(folderPath);
                        final BuildingEditorDialogHGSS dialogHGSS = new BuildingEditorDialogHGSS(handler.getMainFrame());
                        dialogHGSS.init(handler, buildHandler);
                        dialogHGSS.loadGame(selectedDirectory.getPath());
                        dialogHGSS.loadCurrentNsbmd();
                        dialogHGSS.updateView();
                        dialogHGSS.setLocationRelativeTo(handler.getMainFrame());
                        dialogHGSS.setVisible(true);
                    } else if (isBWFolder(folderPath)) {
                        JOptionPane.showMessageDialog(handler.getMainFrame(),
                                "The building editor is not available for BW and BW2 games",
                                "Building editor not available", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(handler.getMainFrame(),
                                "The selected folder is not the game's main folder generated by SDSME",
                                "Error selecting folder", JOptionPane.ERROR_MESSAGE);
                    }
                }
        );
    }

    private static boolean isDPPtFolder(String folderPath) {
        File folder = new File(folderPath + File.separator + "data" + File.separator + "resource");
        return folder.exists();
    }

    private static boolean isHGSSFolder(String folderPath) {
        File folder = new File(folderPath + File.separator + "data" + File.separator + "pbr");
        return folder.exists();
    }

    private static boolean isBWFolder(String folderPath) {
        File folder = new File(folderPath + File.separator + "data" + File.separator + "dl_rom");
        return folder.exists();
    }

}
